FROM node:22.14.0-alpine

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared/ ./shared/
COPY ./apps/api/package.json ./apps/api/pnpm-lock.yaml ./apps/api/

WORKDIR /app/apps/api
RUN pnpm install --frozen-lockfile

COPY ./apps/api .

CMD ["sh", "-c", "pnpm prisma generate && pnpm run seed && pnpm run start:dev"]

