export type CategoriesName = "Appetizers" | "Oysters" | "Mains" | "Dessert";

export type FoodItem = {
  alt: string;
  title: string;
  description: string;
  price: string;
  allergies: string;
  category: CategoriesName;
  allergies_long: string;
  src: string;
};

export type FoodCategory = {
  id: CategoriesName;
  src: string;
  name: string;
  alt: string;
  path: string;
  sortOrder: number;
  promo?: string;
};

export const foodCategories: Record<CategoriesName, FoodCategory> = {
  Appetizers: {
    id: "Appetizers",
    src: "/img/menu/food_menu/volto_wagyu_sandwich.jpg",
    name: "Snacks & Appetizers",
    alt: "Snacks & Appetizers",
    path: "appetizers",
    sortOrder: 0,
  },
  Oysters: {
    id: "Oysters",
    name: "Caviar & Oysters",
    src: "/img/menu/food_menu/oscietra_caviar.jpeg",
    alt: "Caviar & Oysters",
    path: "oysters",
    sortOrder: 2,
  },
  Mains: {
    id: "Mains",
    name: "Mains",
    src: "/img/menu/food_menu/wagyu_striploin.jpg",
    alt: "Mains",
    path: "mains",
    sortOrder: 3,
  },
  Dessert: {
    id: "Dessert",
    name: "Dessert",
    src: "/img/menu/food_menu/volto_chocolate_cake.jpeg",
    alt: "Dessert",
    path: "dessert",
    sortOrder: 4,
  },
};

export const foodData: FoodItem[] = [
  {
    src: "/img/menu/food_menu/edameme_sea_salt.jpg",
    alt: "EDAMAME",
    title: "Edamame",
    price: "4 BD",
    category: "Appetizers",
    description: "Sea salt",
    allergies: "SO, E, S",
    allergies_long: "Soy, Eggs, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/edamame_sweet_miso.jpg",
    alt: "EDAMAME",
    title: "Edamame",
    price: "4.5 BD",
    category: "Appetizers",
    description: "Sweet miso sauce, sesame seeds",
    allergies: "SO, E, S",
    allergies_long: "Soy, Eggs, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/olives.jpg",
    alt: "OLIVES",
    title: "Olives",
    price: "3.6 BD",
    category: "Appetizers",
    description: "Mixed pitted cocktail olives",
    allergies: "V",
    allergies_long: "Vegetarian",
  },
  {
    src: "/img/menu/food_menu/chicken_croquettes.jpg",
    alt: "CHICKEN CROQUETTES",
    title: "Chicken Croquettes",
    price: "4.5 BD",
    category: "Appetizers",
    description: "Chicken, leek, truffle, garlic mayonnaise, and parmesan cheese",
    allergies: "G, D, E",
    allergies_long: "Gluten, Dairy, Eggs",
  },
  {
    src: "/img/menu/food_menu/avocado_chips.jpg",
    alt: "AVOCADO CHIPS",
    title: "Avocado Chips",
    price: "4.8 BD",
    category: "Appetizers",
    description: "Crispy avocado fries, spring onion, sriracha and yoghurt dip",
    allergies: "G, D, E, V",
    allergies_long: "Gluten, Dairy, Eggs, Vegetarian",
  },
  {
    src: "/img/menu/food_menu/volto_nuts.jpg",
    alt: "VOLTO NUTS",
    title: "Volto Nuts",
    price: "3.6 BD",
    category: "Appetizers",
    description: "House-roasted and spiced cashew nuts, almond nuts, and walnuts",
    allergies: "N, V",
    allergies_long: "Nuts, Vegetarian",
  },
  {
    src: "/img/menu/food_menu/prawn_pops.jpg",
    alt: "PRAWN POPS",
    title: "Prawn Pops",
    price: "4.8 BD",
    category: "Appetizers",
    description: "Crispy prawn bites, chives, and teriyaki sauce",
    allergies: "G, D, S, SO",
    allergies_long: "Gluten, Dairy, Fish and Shellfish, Soy",
  },
  {
    src: "/img/menu/food_menu/padron_peppers.jpg",
    alt: "PADRON PEPPERS",
    title: "Padron Peppers",
    price: "4.5 BD",
    category: "Appetizers",
    description: "Fried Spanish green peppers with olive oil and coarse salt",
    allergies: "V",
    allergies_long: "Vegetarian",
  },
  {
    src: "/img/menu/food_menu/volto_greek_salad.jpg",
    alt: "VOLTO GREEK SALAD",
    title: "Volto Greek Salad",
    price: "8 BD",
    category: "Appetizers",
    description: "Ripe tomato, olives, charred peppers, red onion, cucumber, and Greek feta cheese",
    allergies: "D, V",
    allergies_long: "Dairy, Vegetarian",
  },
  {
    src: "/img/menu/food_menu/burrata.jpg",
    alt: "BURRATA",
    title: "Burrata",
    price: "9 BD",
    category: "Appetizers",
    description:
      "Burrata cheese, basil marinated black berries, teen, cherry tomatoes, balsamic vinegar, and olive oil",
    allergies: "D, V, N",
    allergies_long: "Dairy, Vegetarian, Nuts",
  },
  {
    src: "/img/menu/food_menu/green_volto.jpg",
    alt: "GREEN VOLTO",
    title: "Green Volto",
    price: "6.5 BD",
    category: "Appetizers",
    description:
      "Baby gem, asparagus, cucumber, edamame, broccolini, green herbs, and labneh dressing",
    allergies: "D, V, SO",
    allergies_long: "Dairy, Vegetarian, Soy",
  },
  {
    src: "/img/menu/food_menu/tuna_tartare.jpg",
    alt: "TUNA TARTARE",
    title: "Tuna Tartare",
    price: "9 BD",
    category: "Appetizers",
    description:
      "Yellow fin tuna, shallots, gherkins, capers, Japanese mayonnaise, fresh herbs, and seaweed crisps",
    allergies: "S, D, E, G",
    allergies_long: "Fish and Shellfish, Dairy, Eggs, Gluten",
  },
  {
    src: "/img/menu/food_menu/beef_kushiyaki.jpg",
    alt: "BEEF KUSHIYAKI",
    title: "Beef Kushiyaki",
    price: "8 BD",
    category: "Appetizers",
    description:
      "Grilled wagyu beef skewers, spring onion, soy, ginger, pickled cucumber, sesame, and red onion salad",
    allergies: "SO, SS",
    allergies_long: "Soy, Sesame",
  },
  {
    src: "/img/menu/food_menu/volto_wagyu_sandwich.jpg",
    alt: "VOLTO WAGYU SANDWICH",
    title: "Volto Wagyu Sandwich",
    price: "18 BD",
    category: "Appetizers",
    description:
      "Breaded wagyu tenderloin and burger patty, volto 3.0 BBQ sauce, milk bread, and parmesan fries. Recommended medium.",
    allergies: "G, D, SO, E",
    allergies_long: "Gluten, Dairy, Soy, Eggs",
  },
  {
    src: "/img/menu/food_menu/california.jpg",
    alt: "CRAZY SUSHI CALIFORNIA",
    title: "Crazy Sushi California",
    price: "7.5 BD",
    category: "Appetizers",
    description: "Tempura shrimp, crab, avocado, cucumber, nori, spicy mayonnaise",
    allergies: "S. E, SO, SS",
    allergies_long: "Fish and Shellfish, Eggs, Soy, Sesame",
  },
  {
    src: "/img/menu/food_menu/jianto_seafood_balls.jpg",
    alt: "JIANTO SEAFOOD BALLS",
    title: "Jianto Seafood Balls",
    price: "8 BD",
    category: "Appetizers",
    description: "Salmon, shrimp, avocado, spicy mayonnaise",
    allergies: "S, E, SO, SS",
    allergies_long: "Fish and Shellfish, Eggs, Soy, Sesame",
  },
  {
    src: "/img/menu/food_menu/summary_tuna_balls.jpg",
    alt: "SUMMERY TUNA BALLS",
    title: "Summery Tuna Balls",
    price: "8 BD",
    category: "Appetizers",
    description: "Tuna, avocado, cucumber, ponzu sauce",
    allergies: "S, SO, E, SS",
    allergies_long: "Fish and Shellfish, Soy, Eggs, Sesame",
  },
  {
    src: "/img/menu/food_menu/fin_de_claire_oysters_half_a_dozen.jpg",
    alt: "FIN DE CLAIRE OYSTERS HALF A DOZEN",
    title: "Fin De Claire Oysters Half a Dozen",
    price: "16 BD",
    category: "Oysters",
    description: " Pomegranite, shallot and mint oil, Lemon, chilli and crispy bacon, Rockefeller",
    allergies: "S,D,G",
    allergies_long: "Fish and Shellfish, Dairy, Gluten",
  },
  {
    src: "/img/menu/food_menu/fin_de_claire_oysters_dozen.jpg",
    alt: "FIN DE CLAIRE OYSTERS DOZEN",
    title: "Fin De Claire Oysters Dozen",
    price: "28 BD",
    category: "Oysters",
    description: " Pomegranite, shallot and mint oil, Lemon, chilli and crispy bacon, Rockefeller",
    allergies: "S,D,G",
    allergies_long: "Fish and Shellfish, Dairy, Gluten",
  },
  {
    src: "/img/menu/food_menu/oscietra_caviar.jpeg",
    alt: "OSCIETRA CAVIAR",
    title: "Oscietra Caviar - 50g",
    price: "89 BD",
    category: "Oysters",
    description: "Blinis, shallots, chives, sour cream, egg, capers",
    allergies: "E, G, D",
    allergies_long: "Eggs, Gluten, Dairy",
  },
  {
    src: "/img/menu/food_menu/oscietra_caviar.jpeg",
    alt: "OSCIETRA CAVIAR",
    title: "Oscietra Caviar - 125g",
    price: "175 BD",
    category: "Oysters",
    description: "Blinis, shallots, chives, sour cream, egg, capers",
    allergies: "E, G, D",
    allergies_long: "Eggs, Gluten, Dairy",
  },
  {
    src: "/img/menu/food_menu/beef_orzo.jpg",
    alt: "BEEF ORZO",
    title: "Beef Orzo",
    price: "19 BD",
    category: "Mains",
    description:
      "Pulled slow-cooked angus beef short rib, truffle, carrot, mushroom, parmesan orzo, seared foie gras, and parsley",
    allergies: "G,D,E",
    allergies_long: "Gluten, Dairy, Eggs",
  },
  {
    src: "/img/menu/food_menu/seafood_orzo.jpg",
    alt: "SEAFOOD ORZO",
    title: "Seafood Orzo",
    price: "21 BD",
    category: "Mains",
    description: "Gulf shrimps, lobster tail, slow-roasted tomato, Greek feta cheese and chives",
    allergies: "S, G, D, E",
    allergies_long: "Fish and Shellfish, Gluten, Dairy, Eggs",
  },
  {
    src: "/img/menu/food_menu/lobster_tagliatelle.jpg",
    alt: "LOBSTER TAGLIATELLE",
    title: "Lobster Tagliatelle",
    price: "32 BD",
    category: "Mains",
    description:
      "Whole lobster, shellfish and saffron bisque, roasted red peppers, red chili, basil, and charred lemon.",
    allergies: "S,G,D,E",
    allergies_long: "Fish and Shellfish, Gluten, Dairy, Eggs",
  },
  {
    src: "/img/menu/food_menu/wagyu_striploin.jpg",
    alt: "WAGYU STRIPLOIN",
    title: "Wagyu Striploin",
    price: "39 BD",
    category: "Mains",
    description:
      "250gr wagyu striploin grade 8-9, Australia. Chimichurri & mushroom sauce, choice of 1 side",
    allergies: "D",
    allergies_long: "Dairy",
  },
  {
    src: "/img/menu/food_menu/rib_eye.jpg",
    alt: "RIB EYE",
    title: "Rib Eye",
    price: "26.5 BD",
    category: "Mains",
    description:
      "300gr wagyu rib eye grade 4-5, Australia. Chimichurri & mushroom sauce, choice of 1 side",
    allergies: "D",
    allergies_long: "Dairy",
  },
  {
    src: "/img/menu/food_menu/corn_fed_chicken.jpg",
    alt: "CORN FED CHICKEN",
    title: "Corn Fed Chicken",
    price: "10 BD",
    category: "Mains",
    description: "Corn fed chicken breast, chimichurri & mushroom sauce, choice of 1 side",
    allergies: "D",
    allergies_long: "Dairy",
  },
  {
    src: "/img/menu/food_menu/rock_lobster.jpg",
    alt: "ROCK LOBSTER",
    title: "Rock Lobster",
    price: "35 BD",
    category: "Mains",
    description: "800gr rock lobster, Oman. Chimichurri & dill butter sauce, choice of 1 side",
    allergies: "D, S",
    allergies_long: "Dairy, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/prawns.jpg",
    alt: "PRAWNS",
    title: "Prawns",
    price: "16.5 BD",
    category: "Mains",
    description: "4 pcs U10 prawns, Gulf. Chimichurri & dill butter sauce, choice of 1 side",
    allergies: "D, S",
    allergies_long: "Dairy, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/salmon.jpg",
    alt: "SALMON",
    title: "Salmon",
    price: "13.5 BD",
    category: "Mains",
    description: "160gr salmon fillet, Norway. Chimichurri & dill butter sauce, choice of 1 side",
    allergies: "D, S",
    allergies_long: "Dairy, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/seafood_platter.jpeg",
    alt: "SEAFOOD PLATTER",
    title: "Seafood Platter",
    price: "52 BD",
    category: "Mains",
    description:
      "Lobster, 2 pcs U10 prawns, salmon fillet, chimichurri & dill butter sauce, choice of 2 sides",
    allergies: "D, S",
    allergies_long: "Dairy, Fish and Shellfish",
  },
  {
    src: "/img/menu/food_menu/ginger_sponge.jpg",
    alt: "GINGER SPONGE",
    title: "Ginger Sponge",
    price: "5 BD",
    category: "Dessert",
    description:
      "Sticky ginger & treacle sponge, fresh mango, ginger toffee sauce, and vanilla ice cream",
    allergies: "D, E, G",
    allergies_long: "Dairy, Eggs, Gluten",
  },
  {
    src: "/img/menu/food_menu/volto_chocolate_cake.jpeg",
    alt: "CHOCOLATE AND WALNUT CAKE",
    title: "Chocolate and Walnut Cake",
    price: "6.5 BD",
    category: "Dessert",
    description: "Dark chocolate and roasted walnut cake, boozy berries, crème fraiche",
    allergies: "D, E, G, N",
    allergies_long: "Dairy, Eggs, Gluten, Nuts",
  },
  {
    src: "/img/menu/food_menu/fruit_platter.jpeg",
    alt: "FRUIT PLATTER",
    title: "Fruit Platter",
    price: "6 BD",
    category: "Dessert",
    description: "Sliced exotic fruits, berries, and grapes",
    allergies: "V",
    allergies_long: "Vegetarian",
  },
  {
    src: "/img/menu/food_menu/cheese_board.jpeg",
    alt: "CHEESE BOARD",
    title: "Cheese Board",
    price: "11 BD",
    category: "Dessert",
    description:
      "Selection of hard & semi-hard European cheeses, grapes, honey, roasted walnuts, dried apricots and figs, cheese crackers",
    allergies: "D, N, G, E",
    allergies_long: "Dairy, Nuts, Gluten, Eggs",
  },
];
