
services:

  volto-web :
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.web
      
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env
    
    # environment:
    #   - CHOKIDAR_USEPOLLING= true
    #   - WATCHPACK_POLLING= true

    ports:
      - '${WEB_PORT:-3001}:${WEB_PORT:-3001}'

    networks:
      - volto-dev-network

  volto-api :
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.api

    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    ports:
      - '${API_PORT:-3000}:${API_PORT:-3000}'

    depends_on:
      volto-postgres:
        condition: service_started
      volto-redis:
        condition: service_started

    volumes:
      - ../apps/api/src:/app/apps/api/src
      - ../apps/api/prisma:/app/apps/api/prisma
    networks:
      - volto-dev-network

  volto-postgres:
    image: postgres:latest
  
    env_file:
    - ../config/.env.dev
    - ../.env.local
    - ../.env

    ports:
      - '${DB_PORT:-5432}:${DB_PORT:-5432}'
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - volto-dev-network

  volto-redis:
    image: redis:latest

    ports:
      - 6379:6379

    volumes:
      - redis_data:/data
    
    command: ['redis-server', '--appendonly', 'yes'] # enables persistence

    networks:
      - volto-dev-network

  volto-minio:
    image: quay.io/minio/minio:latest
    
    ports:
      - '${MINIO_PORT:-9000}:${MINIO_PORT:-9000}' # S3 API
      - 9001:9001 # Web UI
    
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    volumes:
      - minio_data:/data
    
    command: server /data --console-address ":9001"
    
    networks:
      - volto-dev-network
    

  volto-minio-init:
    image: minio/mc
    depends_on:
      volto-minio:
        condition: service_started

    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    volumes:
      - ../apps/api/src/seed/minio_client_seed_files:/seed # Your seed files
      - ../apps/api/init_minio_client.sh:/init_minio_client.sh # The script

    entrypoint: ['/bin/sh', '/init_minio_client.sh']

    networks:
      - volto-dev-network

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

networks:
  volto-dev-network:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1



