services:
  reverse-proxy:
    container_name: volto-stage-reverse-proxy
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./docker/stage/Dockerfile.stage.caddy
      args:
        VITE_NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${API_URL}

    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - ${ADMIN_PORT}:${ADMIN_PORT}

    networks:
      - default

  api:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./docker/stage/Dockerfile.stage.api

    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}

      API_URL: ${API_URL}
      WEB_URL: ${WEB_URL}
      ADMIN_URL: ${ADMIN_URL}
      ALLOWED_ORIGIN_PATTERNS: ${ALLOWED_ORIGIN_PATTERNS}

      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_CLOUDFRONT_URL: ${AWS_CLOUDFRONT_URL}

      MINIO_Region: ${MINIO_Region}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_PORT: ${MINIO_PORT}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      ONE_SIGNAL_APP_SECRET: ${ONE_SIGNAL_APP_SECRET}
      ONE_SIGNAL_APP_ID: ${ONE_SIGNAL_APP_ID}

      IOS_MIN_SUPPORTED_VER: ${IOS_MIN_SUPPORTED_VER}
      ANDROID_MIN_SUPPORTED_VER: ${ANDROID_MIN_SUPPORTED_VER}

    command: sh -c "pnpm prisma migrate deploy && node dist/main.js"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    networks:
      - default

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} "]
      interval: 5s
      retries: 10
      timeout: 5s

    volumes:
      - db_stage_volume:/var/lib/postgresql/data

    networks:
      - default

  redis:
    image: redis:7.4-alpine

    volumes:
      - redis_stage_volume:/data

    command: ["redis-server", "--appendonly", "yes"] # enables persistence

    networks:
      - default

  minio:
    image: quay.io/minio/minio:latest

    ports:
      - "${MINIO_PORT:-9000}:${MINIO_PORT:-9000}" # S3 API
      - 9001:9001 # Web UI

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio_stage_volume:/data

    command: server /data --console-address ":9001"

    networks:
      - default

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_BUCKET: ${MINIO_BUCKET}

    volumes:
      - ${PROJECT_ROOT}/apps/api/src/seed/minio_client_seed_files:/seed # Your seed files
      - ${PROJECT_ROOT}/apps/api/init_minio_client.sh:/init_minio_client.sh # The script

    entrypoint: ["/bin/sh", "/init_minio_client.sh"]

    networks:
      - default

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - "${SMTP_PORT:-1025}:${SMTP_PORT:-1025}"

    networks:
      - default

  db-backup:
    image: postgres:alpine
    depends_on:
      db:
        condition: service_healthy

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_CONTAINER_NAME: db

    volumes:
      - ${PROJECT_ROOT}/scripts/backup.sh:/backup.sh
      - ${PROJECT_ROOT}/scripts/restore.sh:/restore.sh
      - ${PROJECT_ROOT}/backup:/backup

    entrypoint: /bin/bash

    command: -c "while true; chmod +x /backup.sh;chmod +x /restore.sh; do /backup.sh; sleep 86400; done"

    restart: unless-stopped

    networks:
      - default

volumes:
  db_stage_volume:
    driver: local
  redis_stage_volume:
    driver: local
  minio_stage_volume:
    driver: local

networks:
  default:
    name: volto_stage_network
