
services:

  reverse-proxy:
    container_name: volto-reverse-proxy
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./docker/prod/Dockerfile.multi.prod.caddy
      args:
        VITE_NODE_ENV: ${NODE_ENV}
        VITE_API_URL: ${API_URL}

    expose:
      - 3001

    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      - volto-caddy-data:/data
      - volto-caddy-config:/config

    networks:
      - default


  api :
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ./docker/prod/Dockerfile.prod.api

    environment:
      NODE_ENV: ${NODE_ENV}
      API_PORT: ${API_PORT}

      API_URL: ${API_URL}
      WEB_URL: ${WEB_URL}
      ADMIN_URL: ${ADMIN_URL}

      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_CLOUDFRONT_URL: ${AWS_CLOUDFRONT_URL}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}

      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

      ONE_SIGNAL_APP_SECRET: ${ONE_SIGNAL_APP_SECRET}
      ONE_SIGNAL_APP_ID: ${ONE_SIGNAL_APP_ID}

    command: sh -c "pnpm prisma migrate deploy && node dist/main.js"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  
    networks:
      - default


  db:
    image: postgres:15
  
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} "] 
      interval: 5s
      retries: 10
      timeout: 5s

    volumes:
      - volto-db-volume:/var/lib/postgresql/data

    networks:
      - default


  db-backup:
    image: postgres:alpine
    depends_on:
      db:
        condition: service_healthy
    
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_CONTAINER_NAME: db
    
    volumes:
      - ${PROJECT_ROOT}/script/backup.sh:/backup.sh
      - ${PROJECT_ROOT}/script/restore.sh:/restore.sh
      - ${PROJECT_ROOT}/backup:/backup
    
    entrypoint: /bin/bash
    command: -c "while true; chmod +x /backup.sh;chmod +x /restore.sh; do /backup.sh; sleep 86400; done"

    restart: unless-stopped

    networks:
      - default

  redis:
    image: redis:7.4-alpine

    volumes:
      - volto-redis-volume:/data
    
    command: ['redis-server', '--appendonly', 'yes'] # enables persistence

    networks:
      - default

volumes:
  volto-db-volume:
    driver: local
  volto-redis-volume:
    driver: local
  volto-caddy-data:
    driver: local
  volto-caddy-config:
    driver: local


networks:
  default:
    name: volto-network