
services:

  api :
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.api
      

    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env
    
    ports:
      - '${API_PORT:-3000}:${API_PORT:-3000}'

    environment:
      CHOKIDAR_USEPOLLING: true
      WATCHPACK_POLLING: true

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    volumes:
      - ../apps/api/src:/app/apps/api/src
      - ../apps/api/prisma:/app/apps/api/prisma


  web :
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.web
      
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env
    
    environment:
      CHOKIDAR_USEPOLLING : true
      WATCHPACK_POLLING : true

    ports:
      - '${VITE_WEB_PORT:-3001}:${VITE_WEB_PORT:-3001}'


  admin :
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev.admin
      
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    environment:
      CHOKIDAR_USEPOLLING : true
      WATCHPACK_POLLING : true

    ports:
      - '${VITE_ADMIN_PORT:-3002}:${VITE_ADMIN_PORT:-3002}'
    
    volumes:
      - ../apps/admin/src:/app/apps/admin/src
      - ../apps/admin/prisma:/app/apps/admin/prisma
      - ../apps/admin/public:/app/apps/admin/public
      


  db:
    image: postgres:latest
  
    env_file:
    - ../config/.env.dev
    - ../.env.local
    - ../.env

    ports:
    - '${DB_PORT:-5432}:${DB_PORT:-5432}'


    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 5s
      retries: 10
      timeout: 5s

    volumes:
      - db_data_dev:/var/lib/postgresql/data

  redis:
    image: redis:latest

    ports:
      - 6379:6379

    volumes:
      - redis_data:/data
    
    command: ['redis-server', '--appendonly', 'yes'] # enables persistence


  minio:
    image: quay.io/minio/minio:latest
    
    ports:
      - '${MINIO_PORT:-9000}:${MINIO_PORT:-9000}' # S3 API
      - 9001:9001 # Web UI
    
    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    volumes:
      - minio_data:/data
    
    command: server /data --console-address ":9001"
    
    

  minio-init:
    image: minio/mc
    depends_on:
      minio:
        condition: service_started

    env_file:
      - ../config/.env.dev
      - ../.env.local
      - ../.env

    volumes:
      - ../apps/api/src/seed/minio_client_seed_files:/seed # Your seed files
      - ../apps/api/init_minio_client.sh:/init_minio_client.sh # The script

    entrypoint: ['/bin/sh', '/init_minio_client.sh']


volumes:
  db_data_dev:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

# networks:
#   dev-network:
#     driver: bridge
#     # ! all this shit below is due to wsl and networking issues, idk rlly but fck docker anyway
#     enable_ipv6: false
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.20.0.0/16
#           gateway: 172.20.0.1



