FROM node:22.14.0-alpine

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

ARG APP_PATH=apps/admin
WORKDIR /app

COPY ./shared/ ./shared/
COPY ${APP_PATH}/package.json ${APP_PATH}/pnpm-lock.yaml ${APP_PATH}/

WORKDIR /app/${APP_PATH}
RUN pnpm install

COPY ${APP_PATH} .

CMD ["pnpm", "run", "dev"]
