FROM node:22.14.0-alpine

# Install pnpm globally
RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY ./shared/ ./shared/
COPY ./apps/web/package.json ./apps/web/package-lock.json ./apps/web/

WORKDIR /app/apps/web
RUN pnpm install

COPY ./apps/web .

CMD ["pnpm", "run", "dev"]
