FROM node:22.14.0-alpine AS deps
ARG API_PATH=apps/api
RUN corepack enable
RUN corepack prepare pnpm@10.33.0 --activate
WORKDIR /app

COPY ${API_PATH}/package.json ./${API_PATH}/package.json
COPY ${API_PATH}/pnpm-lock.yaml ./${API_PATH}/pnpm-lock.yaml
COPY ${API_PATH}/pnpm-workspace.yaml ./${API_PATH}/pnpm-workspace.yaml

COPY ${API_PATH}/prisma ./${API_PATH}/prisma/
COPY shared ./shared/  

WORKDIR /app/${API_PATH}
RUN pnpm install --frozen-lockfile

FROM node:22.14.0-alpine AS builder
ARG API_PATH=apps/api
RUN corepack enable
RUN corepack prepare pnpm@10.33.0 --activate

WORKDIR /app
COPY --from=deps /app/${API_PATH}/node_modules ./${API_PATH}/node_modules

WORKDIR /app/${API_PATH}
COPY ${API_PATH}/package.json  ./package.json
COPY ${API_PATH}/pnpm-lock.yaml ./pnpm-lock.yaml
COPY ${API_PATH}/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ${API_PATH}/prisma ./prisma/
RUN pnpm prisma generate

WORKDIR /app
COPY shared ./shared/
COPY ${API_PATH} ./${API_PATH}/

WORKDIR /app/${API_PATH}
COPY ${API_PATH} .

RUN pnpm run build

FROM node:22.14.0-alpine AS runner
ARG API_PATH=apps/api
RUN corepack enable && corepack prepare pnpm@10.33.0 --activate
RUN addgroup -S nodejs && adduser -S nodejs -G nodejs

WORKDIR /app/${API_PATH}

COPY --from=deps /app/${API_PATH}/node_modules ./node_modules
COPY --from=builder ./app/${API_PATH}/package.json ./
COPY --from=builder ./app/${API_PATH}/pnpm-lock.yaml ./
COPY --from=builder  ./app/${API_PATH}/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=builder ./app/${API_PATH}/public ./public
COPY --from=builder ./app/${API_PATH}/templates ./templates
COPY --from=builder /app/${API_PATH}/prisma ./prisma/
COPY --from=builder /app/${API_PATH}/dist ./dist/

USER nodejs
