

@baseUrl = http://voltobahrain.online/api

############################
### Register a new user
# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username":"tigana",
    "email":"tigana137@gmail.com",
    "phoneNumber":"80000000",
    "gender":"M",
    "password":"12345678"
}


### Login request
### Step 1: Get access token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "12345678"
}

### Get current user (uses token from login)
GET {{baseUrl}}/auth/me
Authorization: Bearer {{login.response.body.accessToken}}


