

@baseUrl = http://localhost:3000/api

### Login request
### Step 1: Get access token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@test.test",
    "password": "123456"
}




### Request Reset-Password
# @name requestResetPassword
POST {{baseUrl}}/reset-password/request
Content-Type: application/json

{
    "email": "admin@example.com"
}



### Confirm Reset-Password
# @name confirmResetPassword
POST {{baseUrl}}/reset-password/confirm
Content-Type: application/json

{
    "token": "2f2093d4afe41572743cf6bee39caa49f05b6fa8e4801a44922e70896ffcfcf9",
    "newPassword": "123456789"
}



### Login request
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{confirmResetPassword.response.body.email}}",
    "password": "{{confirmResetPassword.request.body.newPassword}}"
}
