
@baseUrl = http://localhost:3000/api
@baseUrl = https://voltobahrain.online/api


### Login request
### Step 1: Get access token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "12345678"
}


### Get Ladies Night event
# @name getLadiesNightEvent
GET   {{baseUrl}}/events/5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}



### Is Ladies Night Active
# @name isLadiesNightActive
GET     {{baseUrl}}/ladies-night
Content-Type: application/json



### Update Ladies Night
# @name updateLadiesNightEvent
PUT     {{baseUrl}}/events/5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
  "id": "5e3b7f1c-2d4a-4f6e-9a8b-1c2d3e4f5a6b",
  "name": "Ladies Night",
  "description": "Ladies Night",
  "type": "WEEKLY",
  "cronStartDate": "12 15 * * 3",
  "cronEndDate": "15 15 * * 3",  
  "thumbnail": {
    "s3Key": "events/ladies-night-wallpaper.jpg",
    "url": ""
  },
  "video": {
    "s3Key": "events/volto-brunch-1.mp4",
    "url": ""
  }
}




### Get Event By Id
# @name getOneEvent
GET     {{baseUrl}}/events/b6d1e3f4-5a7c-4f2b-8e1a-9c3b2d4f5a6e
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




### Get All Events
# @name getAllEvents
GET     {{baseUrl}}/events?eventType=WEEKLY
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}




### Get List Of Events
# @name getListOfEvents
GET     {{baseUrl}}/events/list?page=1&limit=4
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}





### Update Special Event
# @name updateSpecialEvent
PUT     {{baseUrl}}/events/b6d1e3f4-5a7c-4f2b-8e1a-9c3b2d4f5a6e
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
  "id":"b6d1e3f4-5a7c-4f2b-8e1a-9c3b2d4f5a6e",
  "name": "New Year's Eve",
  "type": "SPECIAL",
  "description": "New Year's Eve",
  "startDate": "2025-10-16T12:35:00.999Z",
  "endDate": "2025-12-31T23:59:59.999Z",
  "cronStartDate": null,
  "cronEndDate": null,
  "thumbnail": {
      "s3Key": "events/new-year-event.jpg",
      "url": "http://localhost:9000/volto/events/new-year-event.jpg"
    },
    "video": {
      "s3Key": "events/volto-video3.mp4",
      "url": "http://localhost:9000/volto/events/volto-video3.mp4"
    }

}


### Create Special Event
# @name createSpecialEvent
POST     {{baseUrl}}/events/
Content-Type: application/json
Authorization: Bearer {{login.response.body.accessToken}}

{
  "name": "New Year's Evesqdssqdqd22",
  "type": "SPECIAL",
  "description": "New Year's Eve22",
  "startDate": "{{$datetime iso8601}}",
  "endDate": "2025-12-31T23:59:59.999Z",
  "thumbnail": {
      "s3Key": "events/new-year-event.jpg",
      "url": "http://localhost:9000/volto/events/new-year-event.jpg"
    },
    "video": {
      "s3Key": "events/volto-video3.mp4",
      "url": "http://localhost:9000/volto/events/volto-video3.mp4"
    }

}




### Get Closest Event
# @name getListOfEvents
GET     {{baseUrl}}/events/closest-event
Content-Type: application/json


