FROM node:22.14.0-alpine AS deps
ARG API_PATH=apps/api
RUN corepack enable
RUN corepack prepare pnpm@latest --activate
WORKDIR /app/${API_PATH}

COPY ${API_PATH}/package.json .
COPY ${API_PATH}/pnpm-lock.yaml .
COPY ${API_PATH}/pnpm-workspace.yaml .

COPY ${API_PATH}/prisma ./prisma/
RUN pnpm install --frozen-lockfile
RUN pnpm approve-builds --global
# RUN pnpm prune --prod



FROM deps AS builder
ARG API_PATH=apps/api

WORKDIR /app
COPY /shared /shared

WORKDIR /app/${API_PATH}
COPY ${API_PATH} .
RUN pnpm run build



FROM deps AS runner
ARG API_PATH=apps/api
# WORKDIR /app/${API_PATH}
# RUN pnpm prune --prod
RUN addgroup -S nodejs && adduser -S nodejs -G nodejs
WORKDIR /app/${API_PATH}

COPY --from=builder /app/${API_PATH}/package.json ./
COPY --from=builder /app/${API_PATH}/dist ./dist/
COPY --from=builder /app/${API_PATH}/public ./public/
COPY --from=builder /app/${API_PATH}/templates ./templates/
COPY --from=builder /app/${API_PATH}/prisma ./prisma/

# Optional: prune unnecessary files
RUN rm -rf node_modules/.pnpm/*/node_modules/.bin \
    && find node_modules -name "*.md" -delete \
    && find node_modules -name "*.map" -delete

COPY ${API_PATH}/public /app/public/
# USER nodejs
CMD ["node", "dist/main.js"]